### ISSUE TITLE
New FastCGI-interface for GT.M available

### ISSUE THREAD

**Issue by Winfried-Bantel** [FastCGI-Archives/fastcgi-archives.github.io#3]
Hello,

we've deployed an interface for the NoSQL-Database GT.M (fis-gtm is a debian-package).
https://github.com/informatik-aalen/FastCGI-for-GT.M

Could You please anounce this at https://fastcgi-archives.github.io/

Thank You

Winfried

**Comment by mcarbonneaux** [comment]
commited [her](https://github.com/FastCGI-Archives/fastcgi-archives.github.io/commit/c79b416d2e5d2c435af12b74d70488914fc0bbc1)
